baseURL = "https://signalpillar.github.io/"
languageCode = "en-us"
title = "Notes to self"
theme = "noteworthy"
publishDir = "public"

enableRobotsTXT = true

[params]
  AuthorName = "Volodymyr Vitvitskyi"
  GitHubUser = "signalpillar"
  Subtitle = "experiment"
